### PR TITLE
Upload Recipes to PFC and start running

### PR DESCRIPTION
**Pull request by rwdavis513**
Added a cli to make it facilitate uploading recipes to the PFC and starting them after uploaded.

### CODE REVIEW

**Review by novemberalpha — APPROVED** [review]
LGTM

**Comment by rwdavis513** [comment]
@rbaynes or @jakerye Could one of you please review this PR?

**Review by sp4ghet — APPROVED** [review]
Looks good, these are just QoL scripts right?

**Comment by rwdavis513** [comment]
@Spaghet Yes these are just supplemental scripts to help with running recipes remotely.

Features:
- Upload recipe to PFC or a list of PFCs
- Start/Stop recipe on PFC

**Comment by sp4ghet** [comment]
Cool, sounds good.

**Pull request merged**
